### ISSUE TITLE
Testing Support for custom environments

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#108]
## Current behavior
Automated testing currently builds and runs on ubuntu-latest and macos-latest environments.

## Expected behavior
Need to be about to test some customized tool chains, in particular a centos/rhel 7 environment using gcc 4.8.5.

Propose using a docker container action (which can run on the github hosted ubuntu vm) to define some custom test environments.

https://help.github.com/en/actions/creating-actions/creating-a-docker-container-action

**Comment by ZacharyWills** [comment]
Will look into this in my fork, will add docker file for software build also.

https://github.com/ZacharyWills/ngen

**Comment by ZacharyWills** [comment]
@hellkite500 Should I add an install doc in this issue also? Separate PRs but based on the same issue?

**Comment by hellkite500** [comment]
> @hellkite500 Should I add an install doc in this issue also? Separate PRs but based on the same issue?

I would open a new issue, keep this one for a technical disscussion around automated testing of custom environment, i.e. not the base ubuntu-latest and macos-latest that we currently have tests for.

**Comment by ZacharyWills** [comment]
Check Dockerfile in PR #120 
Works with RHEL Universal Basic Image for RHEL8

**Comment by ZacharyWills** [comment]
Can we close now that multiple ENVs are working?

**Comment by hellkite500** [comment]
Do we have a CI test running using the centos/gcc 4.8.5?  That was the intent of this issue was to make sure we get an action running that can test this compiler along with newer versions.

**Comment by ZacharyWills** [comment]
Currently they're running on centos 8 with `gcc-8.3.1-5.el8.0.2.x86_64`   &   `gcc-c++-8.3.1-5.el8.0.2.x86_64`

If we need a different version for compatibility we should make that as a new action or I can convert the current. Difficult to test it until #201 clears though.
