### ISSUE TITLE
Adjustments getting reservoir response in Tshirt model

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/ngen#128]
The usage of the _Reservoir::response_meters_per_second_ function in the _tshirt_model_ class is not entirely correct/consistent, especially regarding parameters obtained from Schaake partitioning.  These need to be corrected.

More generally, it should be considered whether the function's parameter for how much new water is being introduced should be a depth-type value in the form of meters (thereby implicitly meters per timestep), or a volumetric value with units of meters per second (as is currently the case).

**Comment by jdmattern-noaa** [comment]
@robertbartel PR #130 would change this from response_meters_per_second  to response_meters in only the depth-type value as you suggest. We could further discuss if we want to fully replace the existing reservoir class with the timeless reservoir.

**Comment by jdmattern-noaa** [comment]
@robertbartel Do you agree that issue can now be closed?
