### ISSUE TITLE
HYMOD README.md should reflect changes made to HYMOD 

### ISSUE THREAD

**Issue by ZacharyWills** [NOAA-OWP/ngen#13]
HYMOD changes should be described here:
https://github.com/NOAA-OWP/ngen/blob/master/models/hymod/include/Hymod.h

## Current behavior
I copied the HYMOD README.md from the repository but we changed some things in our implementation. These should be reflected by changing the README.md from the original to reflect any changes.

## Expected behavior
HYMOD should have a README that describes our version used for ngen

## Steps to replicate behavior (include URLs)

1.

**Comment by hellkite500** [comment]
The HYMOD implementation we have was independently implemented, probably from the same reference paper, but has no direct relation to https://github.com/jdherman/hymod
