### ISSUE TITLE
Request: Link GitHub.io page in readme

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/ngen#135]
It would be beneficial as a user and potential contributor if a link to the project specific GitHub Pages were linked in the _About_ or root level readme. I would be happy to open a PR adding this to the readme if you all see fit.

**Comment by christophertubbs** [comment]
Heck, this can probably just be done in the web editor. I don't see why not. Several of the markdown files just appear to be stubs from the template, so I don't see a lot of risk, unless you're going to put in nefarious links. In which case "Bad, Austin, bad!"

**Comment by aaraney** [comment]
But chris if you aren't using vim are you really doing work? (for sure doing it in the web editor). You know me, nefarious is just an alias to Austin anyways. Ill see what I can do
