### ISSUE TITLE
Automatically Run NGen on PR

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/ngen#141]
We currently have the data needed to run the driver packed into the repo. As of this writing, if you clone the repo and try to run it, it _should_ be able to run. Unfortunately, some of the sample data was moved, invalidating some of the paths in the driver. It's a small, easy change, but it would have been nice if a message was created on the PR generation stating "Hey, this will error out".

It will probably be helpful to run this in the testing action and assert that the exit code was correct in order to make sure it was able to run until completion.

**Comment by ZacharyWills** [comment]
As a bit of a progression of this, would a configurable input data location make this easier? Not sure how that might work with the various models, but it should be discussed.

**Comment by christophertubbs** [comment]
I think, optimally, these paths would be command line parameters, so I agree. Baking the path to a crosswalk into the binary doesn't quite sound optimal (unless it's super generic, which it isn't).

Regardless, we should try running all this through NGen itself before changes are approved.

**Comment by hellkite500** [comment]
Is the intent of this issue to have an "engineering" test where changes in output are compared?  Or simply to exercise the driver and a test config to make sure nothing crashes or fails?

**Comment by christophertubbs** [comment]
The latter. "I changed the spark plugs; does it crank up?" It doesn't mean that the engine necessarily runs as it should, but it runs.

The unit tests can help check to see if the bits and pieces work, but everything is being developed in such a distributed fashion that we could work for weeks and **never** notice that it no longer works as a system.

**Comment by hellkite500** [comment]
For reference, an alpine based docker image that builds and can run ngen exists here: https://github.com/NOAA-OWP/DMOD/tree/master/docker/main/ngen

**Comment by ZacharyWills** [comment]
Can we get the example data relative paths so the action can point at those from arguments to the binary.

**Comment by hellkite500** [comment]
https://github.com/NOAA-OWP/ngen/blob/15c50cbdee1b6da28b40bb6b3546edfbe5318270/src/NGen.cpp#L109

If the `ngen` binary and `data` dir are in the same `WORKDIR`, then something like
`ngen data/catchment_data.geojson "" data/nexus_data.geojson "" data/example_realization_config.json`

**Comment by ZacharyWills** [comment]
I'll work on a new Action to run the model on PR with the test/example data.

**Comment by ZacharyWills** [comment]
As an update I hav this working locally, it's just not running the model, so I need some help clearing the faults in #173 and once I get it to run once we can set it up to run on PR.

**Comment by ZacharyWills** [comment]
Almost finished, it'll run on PR to master.

**Comment by ZacharyWills** [comment]
This has been added and running for a while, do we need anything else to close? @christophertubbs

**Comment by hellkite500** [comment]
@ZacharyWills once #201 is resolved then we can close this.  To be clear, this isn't actually running the ngen PR, it is running the upstream base on PR.
