### ISSUE TITLE
Follow up for formulation manager

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#156]
Need to review comments on #147 and open issues to address some of the refactoring and cleanup that was mentioned in that PR.  The PR was merged to allow other work to continue in development, but some of the noted changes need to be addressed.

**Comment by ZacharyWills** [comment]
How granular do you want the issues? One per comment? Also @donaldwj mentioned 

https://github.com/NOAA-OWP/ngen/pull/147#discussion_r475822874

> formal interface for json serialization and de-serialization that should implemented by all data objects

Should that be it's own Feature request?
