### ISSUE TITLE
Command Line Args

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#159]
## Current behavior
All configuration files and options are hard coded into NGen.cpp.

## Expected behavior
Should be able to run different configurations and enable different options without the need to recompile.

## Proposal
Add a command line option parsing capability.
This can be done in several ways
- Roll our own
- Use a linked library like `Boost::Program_Options`
- Use a header only parsing library

I found this library that looks promising as a header only command line parser that should facilitate all our foreseeable use cases, and can be included as a sub-module in our project.

https://github.com/CLIUtils/CLI11

@NOAA-OWP/next-gen any thoughts or other considerations?

**Comment by hellkite500** [comment]
Ignore the link above, referenced the wrong issue # above.  Could fix but would have to rebase the merged history, not gonna worry about it for now.

**Comment by jdmattern-noaa** [comment]
I am working on this. @jdmattern-noaa

**Comment by mhe-ert** [comment]
OWP Post Processing uses a command line parser from IWRSS (Integrated Water Resources Science and Services). We can borrow the code for this issue.

**Comment by hellkite500** [comment]
@mhe-ert is the parser available open source? Is it linked as a library or header only?  If you can provide any links and/or documentation it would help to continue this disscussion.
