### ISSUE TITLE
Need time information more directly connected to model input/output

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#170]
Need simulation date/time ranges passed as explicitly to the simulation engine.  This simulation range should then be forwared to the forcing objects to configure the amount of forcing they load.  Also, the output should use this time information to write an actual time series.

## Current behavior
The only time input information is nested in the forcing configuration.  The time range is used by the forcing objects, but is not tightly coupled to the simulation loop, which at this point is a hard coded loop over a fixed number of time steps (assumed hourly).  The outputs are relative to these loop iterations, and are not easily associated with the data/time the output is simulated for.

## Expected behavior
Configuration passes a simulation start/end time, as either explicit dates, or start date + simulation time, or some other means.  The simulation start and end times are then passed to the forcing object construction to read the required forcings.  The main simulation loop needs to iterate over this time period, and needs to add the date/time as the output index.

**Comment by jdmattern-noaa** [comment]
Closing via PR #190 merged into master.
