### ISSUE TITLE
Inconsistent behavior reading realization config

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/ngen#171]
In some development environments, realization config files do not have their contained properties read correctly by the main **_ngen_** executable, created by building the `ngen` CMake target, even though they are present.  However, in certain other environments, the same files are read and used without issue.

The same version of Boost (1.72.0) was present in both the problematic and non-problematic environments tested thus far.

## Current behavior

In some but not all environments, when running the built _**ngen**_ executable, it exits with the follow error, even if the realization config file it was passed is not actually missing the referenced property (here `maxsmc`).

```
...
[100%] Built target ngen
Hello there 0.1.0
Building Nexus collection
Building Catchment collection
terminate called after throwing an instance of 'std::runtime_error'
  what():  A tshirt_c formulation cannot be created; the following parameters are missing: maxsmc
/bin/bash: line 1:   480 Aborted                 ./cmake-build-dir/ngen data/example_case_tshirt_c_realization/catchment_data.geojson cat-89 data/example_case_tshirt_c_realization/nexus_data.geojson nex-92 data/example_case_tshirt_c_realization/realization_config.json
```

## Expected behavior

The expected behavior is that the file will load properly (assuming it is both valid and complete) and allow the driver to execute the correct model and parameter configuration.

## Steps to replicate behavior (include URLs)

1. Ensure a CMake build system directory has been generated.
2. Ensure the local copy is up to date with the _upstream_ `master` branch
3. Build the CMake `ngen` target
4. Run the built _**ngen**_ executable, supplying the appropriate arguments, including the necessary configuration files (see its error message for arg list)

#### Known Effected Environments (:x:)

- CenOS 7.8 on Docker
- RHEL 7.8 on dev_vm

#### Known Uneffected Environments (:white_check_mark:)

- MacOS 10.15.4
- Ubuntu 20.10 on Docker

##### CentOS 7.8 on Docker (:x:)
Custom Docker image based on the CentOS image at tag `7.8.2003`:
```
[root@07247c000c76 repo]# cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[root@07247c000c76 repo]# gcc-         
gcc-ar      gcc-nm      gcc-ranlib  
[root@07247c000c76 repo]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@07247c000c76 repo]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

##### dev_vm on RHEL 7.8 (:x:)

It has also been seen on _dev_vm_.  In particular, it looks to use the same GCC version:

```
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

##### MacOS 10.15.4 (:white_check_mark:)

The problem is not being seen on a MacBook.

```
cmake version 3.16.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

##### Ubuntu 20.10 on Docker (:white_check_mark:)

Later testing demonstrated this environment does not experience the issue, further suggesting it is a problem in older versions of the required tools.

```
root@7b1b409be209:/repo# cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
root@7b1b409be209:/repo# 
root@7b1b409be209:/repo# 
root@7b1b409be209:/repo# 
root@7b1b409be209:/repo# 
root@7b1b409be209:/repo# 
root@7b1b409be209:/repo# gcc --version
gcc (Ubuntu 10.2.0-9ubuntu2) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@7b1b409be209:/repo# 
root@7b1b409be209:/repo# 
root@7b1b409be209:/repo# 
root@7b1b409be209:/repo# 
root@7b1b409be209:/repo# 
root@7b1b409be209:/repo# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Groovy Gorilla (development branch)"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
```

**Comment by stcui007** [comment]
In Fred's t-shirt C-code, the maxsmc is named smcmax, could this
cause problem?
It seems unlikely as it works for one system already. Just some wild
thought.

Shengting

**Comment by robertbartel** [comment]
@stcui007, no, the error is occurring before execution gets to the actual model logic.  I am pretty sure I've accounted for their being two variants of that property's name.  Regardless, I don't think this type of thing can explain the inconsistency when using the same code and same config file in different build environments.

**Comment by robertbartel** [comment]
I've edited the original description to reflect another tested case.  It appears that Ubuntu 20.10 on Docker is free from this issue, although I suspect it's more due to the use of a new GCC version.

**Comment by stcui007** [comment]
Could this be tested using a newer version of gcc in Rhel or CentOS?
I seem to remember asking them to install a newer version of gcc on
apd-dev1 before, but can't be absolutely sure.

**Comment by hellkite500** [comment]
@robertbartel can you attach the config that is producing the error?

**Comment by robertbartel** [comment]
@hellkite500, Github doesn't like when I attempt to drag the files in to attach them, so I've just forwarded the email to you where I originally sent them out.  They are modified from what is in the repo, both to ensure usage of the `tshirt_c` realization and to strip out all but one essential catchment and nexus (otherwise, there is a separate issue causing problems).

**Comment by hellkite500** [comment]
@robertbartel Thanks.  The separate issue may have been caused by #175 if you were trying to run with an empty string arg for the subsets (to run all).

**Comment by hellkite500** [comment]
So the reason it fails is because of this line
https://github.com/NOAA-OWP/ngen/blob/235cadca69b7c11e48580bdec32c9fa9e25b8bc2/include/realizations/catchment/Formulation.hpp#L70
Where the parameter is consider *missing* by checking its count in the options.  The test here though checks for `count != 0` which will always be true if the parameter exists since count will be 1 if the parameter is in the option map.  By this logic, an existing param will always be considered missing.  Changing to ` if (options.count(parameter) == 0) {` makes this work on the failing currently failing gcc environment.

The next big question is why does it NOT fail in the currently "working" environments?

**Comment by hellkite500** [comment]
So along with the previous noted bug in count logic, this is also an issue:
https://github.com/NOAA-OWP/ngen/blob/235cadca69b7c11e48580bdec32c9fa9e25b8bc2/include/realizations/catchment/Formulation.hpp#L65

The `sizeof(required_parameters[0])` is the size of the string stored in the array at this index.  The `sizeof` the string is platform dependent, on the currently "working" systems, (macos/clang being verified) this value is 24, and `sizeof(required_parameters)` is 8, so the parameter count becomes 0 and the missing check is never performed (which is why the above bug wasn't seen on these "working" environments.  On the failing centos/gcc 4.8.5 the `sizeof(required_parameters[0])` is 8, giving a count of 8/8 = 1.  So 1 parameter is checked, and due to the logic error in the check it automatically fails.

**Comment by stcui007** [comment]
Good detective work. I just tested and it worked.
Currently I don't see runoff and flow info in the output.
