### ISSUE TITLE
NGEN seg faults

### ISSUE THREAD

**Issue by ZacharyWills** [NOAA-OWP/ngen#173]
While working on #141 I encountered these issues:
## Current behavior
With the refactored_example_realization_config.json: 
```
[ngen]# ./ngen data/catchment_data.geojson "" data/nexus_data.geojson "" data/refactored_example_realization_config.json
Hello there 0.1.0
Building Nexus collection
Building Catchment collection
Running Models
Time step 0
Pass-through kernel being used for GIUH calculations; raw input value `0` being passed through and immediately returned as output.
        Catchment cat-87 contributing 0.000301563 m/s to 
Segmentation fault

```
and with the data/example_realization_config.json
```
[ngen]# ./ngen data/catchment_data.geojson "" data/nexus_data.geojson "" data/example_realization_config.json
Hello there 0.1.0
Building Nexus collection
Building Catchment collection
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted
```

## Expected behavior
NGEN should run over the test data.

## Steps to replicate behavior (include URLs)

1. Build the 'ngen' target and run with the command Nels posted in #141 

## Screenshots

<img width="1031" alt="Screen Shot 2020-09-21 at 2 32 23 PM" src="https://user-images.githubusercontent.com/60660437/93812466-46c53c80-fc17-11ea-9ffa-b0543ca1417e.png">

**Comment by ZacharyWills** [comment]
@christophertubbs Didn't you make the original example_realization_config.json? I think I might need your assistance.

**Comment by hellkite500** [comment]
This issue arises from the CLI parsing of the subset strings.  An empty string `""` gets added to the subset id vector, which is no longer empty, so the feature building doesn't add any features to the feature collection, but the realization manager isn't directly connected to the feature collection, so it still tries to run the model, but when feature information is accessed, it breaks.  A fix should be up shortly.
