### ISSUE TITLE
Add Hy_HydroLocation 

### ISSUE THREAD

**Issue by donaldwj** [NOAA-OWP/ngen#185]
Nexus concept implementation needs to decouple the _realization_ from the topological/conceptual nexus.  To do this, a HY_HydroLocation is needed.

Required:

Add the Hy_HydroLocation Classes to the model architecture.
Refactor PointNexus to be a _realized_ Nexus at a `HY_HydroLocation` of `CatchmentOutlet` enum type.

# References:
[HydroFeature Application Schema Diagram](http://docs.opengeospatial.org/is/14-111r6/14-111r6.html#figure21)
[Hydro Nexus Realization](http://docs.opengeospatial.org/is/14-111r6/14-111r6.html#figure35)

**Comment by hellkite500** [comment]
Closed by #156, more complete implementation in #249
