### ISSUE TITLE
Create a collection of HY_Catchment objects to iterate through in the driver instead of formulation objects

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/ngen#195]
The driver currently builds up a collection of catchment features, builds up a collection of formulations based on those catchments, then iterates upon those formulations to generate their results. Instead, HY_Catchment objects should be created from the get-go and *those* should be iterated through since they all contain the formulations needed.

This can be found around lines 169 and 174 of `ngen.cpp`.

**Comment by hellkite500** [comment]
With that in place, there should be 1-1 correspondence between hydrofabric catchment graph and the formulation manager, then we  could iterate the features and access the relevant HY_Catchment/Formulation via the fomulation manger `get_formulation(std::string id)`.  This isn't as direct, but gets closer.  This might actually be useful to maintain some differentiation between the topology and the implementation of fomulations.
