### ISSUE TITLE
MPI Distributed Processing Design Plan

### ISSUE THREAD

**Issue by jdmattern-noaa** [NOAA-OWP/ngen#224]
Initial MPI distributed processing design plan:

@jdmattern-noaa will subclass Nexus and create a `RemoteNexus` that is able to `send` from the upstream and `receive`  at the downstream.  Also will add some CMAKE configuration options for `USE_MPI`

@stcui007 is going to prototype a distributed driver which initially just calls `MPI_INIT` and then creates two arbitrary catchment objects connected by one `Nexus` object.  Once the `RemoteNexus` is ready, replace the `Nexus` with `RemoteNexus` and test the communication on two processors.

From here, we will work to connect this to the whole hydrofabric and test an "extreme" distribution -- every catchment its own process -- just to ensure the communication is working properly.

Finally, develop a reasonable initial decomposition mechanic that works on the hydrofabric graph to partition work (catchments) on processors that are connected appropriately by `RemoteNexus`

**Comment by stcui007** [comment]
Thanks, David.

Shengting

**Comment by hellkite500** [comment]
Nexus class getting updated to async send/recieve, driver integration in progress #229

**Comment by ZacharyWills** [comment]
In this case is the remote nexus still a hydrological entity or the computational entity (just trying to figure out is the nexus asked for a single nexus' information or for the nexus' information that might be on that host in particular)?

**Comment by jdmattern-noaa** [comment]
> In this case is the remote nexus still a hydrological entity or the computational entity (just trying to figure out is the nexus asked for a single nexus' information or for the nexus' information that might be on that host in particular)?

The nexus would still be considered one hydrological entity but potentially split among multiple processes passing info from upstream to downstream connections.

**Comment by hellkite500** [comment]
Per meeting disscussion:

Initial hydro partitioning will be done externally, producing a json file something like this:
```json
{
    "partitions: [
        {"id":0, "cat-ids":["cat-1","cat-2"], "nex-ids"["nex-1", "nex-2"], "remote-up":[], "remote-down":[ {id:"nex-2"], "partition":1 },
         {"id":1, "cat-ids":["cat-3","cat-4"], "nex-ids"["nex-2", "nex-3"], "remote-up":[ {id:"nex-2", "partition":0], "remote-down":[] }
     ]
}
```
Let each MPI rank read global hydrobric and `prepare_features`, then we can use the partition file information to extract from the global feature collection the ids associated with a single partition for each rank.  Then formulation manager manages the local partition catchments, create local nexus instances except where partition indicates up/downstream remote is needed, it then creates the correct up or down stream nexus where the sender/reciever is indicated by the remote partition.

**Comment by hellkite500** [comment]
More discussion on the partition spec in related issue #253, and implementation of partition generator in #258, #269, and #287.
