### ISSUE TITLE
A distributed driver using MPI

### ISSUE THREAD

**Issue by stcui007** [NOAA-OWP/ngen#228]
A prototype distributed driver that runs in MPI environment 

## Current behavior
Issues:.
This version run MPI job only, but could be easily modified to run both serial and MPI jobs.
Currently input data are hard coded.
prepare_features(...) function causes runtime error in MPI environment.

## Expected behavior
Unified driver that run serial job as well as MPI jobs

## Steps to replicate behavior (include URLs)
Source code link:
https://github.com/stcui007/ngen/blob/mpi-dev/src/NGen.cpp

Build:
cmake -DCMAKE_BUILD_TYPE=Debug -B cmake-mpi-debug -DMPI_ACTIVE:BOOL=ON -S .
cmake --build cmake-mpi-debug --target ngen -- -j 4

Run:
mpirun -np 2 ./cmake-mpi-debug/ngen ./data/catchment_data.geojson "" ./data/nexus_data.geojson "" ./data/example_realization_config.json

**Comment by hellkite500** [comment]
Distributed driver implementation in #275 covers this issue.
