### ISSUE TITLE
Docker build for PR testing of simple run doesn't actually run the changed code

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#233]
The workflow for testing a simple model run using the ngen engine builds a docker container to run the test:
https://github.com/NOAA-OWP/ngen/blob/5d7b96cac7c70aad1bc9db4f20913fc030b97c96/.github/workflows/Example_model_run.yml#L13

But this container checks out the master branch of the repository to run the test on, so it doesn't make much sense to include it as a PR test.

https://github.com/NOAA-OWP/ngen/blob/5d7b96cac7c70aad1bc9db4f20913fc030b97c96/docker/CENTOS_NGEN_RUN.dockerfile#L6

We should either drop it from the PR tests, or make sure it is using the checkout out PR branch from the checkout action to build before it runs.

**Comment by ZacharyWills** [comment]
Once we have confirmed PR branches are run on PR, we can close this
