### ISSUE TITLE
Compile/INSTALL instructions on Linux and other systems

### ISSUE THREAD

**Issue by rburghol** [NOAA-OWP/ngen#234]
The goal of this issue is to contribute to the development of the INSTALL file for the ngen project.
I am documenting my own process as an outside user with a fresh system who is interested in exploring the install package of this model system.  I will lay our some basic trial and errors of my own, and hopefully if other experienced folks have time they can give me an assist where applicable.  

## Current behavior
- INSTALL text is a placeholder

## Expected behavior
- INSTALL text should include basic process to install and run simple simulation on a few common systems:
  - [ ] Linux 
    - [x] Ubuntu 20.04
    - [ ] CentOS
  - [ ] MacOS
  - [ ] Other

### Ubuntu 20.04
```
# Get the source
git clone https://github.com/NOAA-OWP/ngen.git ngen
cd ngen
# Grab the Goole testing dependency
git submodule update --init --recursive -- test/googletest
mkdir cmake-build-dir/
cmake -B cmake-build-dir -S .
cmake -B cmake-build-dir -DBMI_C_LIB_ACTIVE:BOOL=OFF -S .
cmake --build cmake-build-dir --target ngen

# Tests
mkdir cmake-build-debug
cmake --build cmake-build-dir --target test_bmi_c
cmake -DCMAKE_BUILD_TYPE=Debug -B cmake-build-debug -S .
cmake --build cmake-build-debug --target test_all -- -j 4
# Finally, run test_all
./cmake-build-debug/test/test_all

# Run a watershed simulation
./cmake-build-dir/ngen ./data/catchment_data.geojson "" ./data/nexus_data.geojson "" ./data/example_realization_config.json

```

## Steps to replicate behavior (include URLs)

1.

**Comment by rburghol** [comment]
## Ubuntu Linux

```
apt-get install cmake
apt-get install Boost.Geometry
cmake ./

```

**Comment by hellkite500** [comment]
Thanks for bringing this up.  While we have yet to more sufficiently document succinct install instructions in our INSTALL.md, we do have detailed documentation on the [dependencies](https://github.com/NOAA-OWP/ngen/blob/master/doc/DEPENDENCIES.md) and [building](https://github.com/NOAA-OWP/ngen/blob/master/doc/BUILDS_AND_CMAKE.md) the application.  These build steps are applicable to any system that satisfies the dependencies, and the build can be used to `make install` the binary.

**Comment by rburghol** [comment]
Awesome - thanks!  If you think there is no need to chip away at a succinct set for INSTALL.md I can go ahead and close this thread.  But if you'd like to use this as a place for that doc development, I am happy to keep it open and contribute.

**Comment by rburghol** [comment]
Boost install on Ubuntu 20.04
- Release packages include boost 1.71.x, which is 1 below the requirement, so had to install boost headers manually.
- Boost header install instructions imply that all one needs to do is to put boost-x.xx.x directory in the BOOST_ROOT variable (from what I could tell), however, the actual boost headers are in boost-x.xx.x/boost, and cmake therefore fails to find the boost version.hpp with ```file STRINGS file "/usr/include/boost/version.hpp" cannot be read.``` (cmake 3.16 in Ubuntu).

Solution:
- create symbolic link to boost install, for example: ```sudo ln /usr/local/src/boost_1_75_0/boost /usr/include/boost  -s```
- set the BOOST_ROOT var, by adding a path export file "boost.sh" to /etc/profile.d, i.e. "/etc/profile.d/boost.sh"
 ```
#!/bin/sh
BOOST_ROOT="/usr/include/boost"
export BOOST_ROOT

```

**Comment by hellkite500** [comment]
Thanks for documenting that.  FYI we do use a Ubuntu github runner to run unit tests, and it doesn't look like it required any additional manipulation of boost.  The runner is currently using Ubunto 20.04.  You can take a look at the steps [here](https://github.com/NOAA-OWP/ngen/blob/master/.github/workflows/test_and_validate.yml).  We also have a tested centos 8 dockerfile [here](https://github.com/NOAA-OWP/ngen/blob/master/docker/CENTOS_NGEN_RUN.dockerfile) that builds and runs a small example input.

> Awesome - thanks! If you think there is no need to chip away at a succinct set for INSTALL.md I can go ahead and close this thread. But if you'd like to use this as a place for that doc development, I am happy to keep it open and contribute.

With regards to keeping this open, we can definitely add some extra information into that document.  At the very least it should probably link to our build documentation until we get to a point we can think about binary distribution/installation.

**Comment by rburghol** [comment]
Thanks.  I will look to see if I can determine why my boost install on 20.04 was problematic. This system is *mostly* fresh, but I have added a non-standard repo to allow access to the geospatial libs that postGIS uses, and perhaps that is where the 1.71 package is being brought into the mix (apt update doesn't go beyond 1.71).

**Comment by rburghol** [comment]
Update: the instructions at the top of this issue now successfully compile the ngen executable. I say *successful* though I can not yet run the example given in the README.md as of yet, with ```./cmake-build-dir/ngen ./data/catchment_data.geojson "cat-88,cat-89" ./data/nexus_data.geojson "nex-92" ./data/example_realization_config.json``` resulting in a core dump:
```
Hello there 0.1.0
Building Nexus collection
Building Catchment collection
terminate called after throwing an instance of 'std::runtime_error'
  what():  A simple_lumped formulation cannot be created; the following parameters are missing: gw_storage, gw_max_storage, nash_max_storage, smax
Aborted (core dumped)
```

**Comment by hellkite500** [comment]
#232 should fix the runtime_error.  There is also another nuance that I'm looking into now where the `realization_configuration.json` contains keys that don't exist in the `catchment_data.geojson`.  Ultimately, the example hydrofabric got updated and the example part of the  readme didn't.  You can apply the updates in the PR and then simply run all the catchments by not providing the subset ids:

```
./cmake-build-dir/ngen ./data/catchment_data.geojson "" ./data/nexus_data.geojson "" ./data/example_realization_config.json
```
And it should work.  I'm working on a patch to clean up the subset handling, once that is in then I will update the example in the readme to something like this, which will run two model formulations on two catchments, but not model the third:

```
./cmake-build-debug/ngen ./data/catchment_data.geojson "cat-27,cat-52" ./data/nexus_data.geojson "nex-26,nex-34" ./data/example_realization_config.json
```

**Comment by hellkite500** [comment]
#236 and #237 are the relevant parts of the problem.

**Comment by rburghol** [comment]
Thanks a bunch, I will check this out ASAP.

**Comment by hellkite500** [comment]
@rburghol those have both been merged into the master branch, so a fresh clone or a pull/rebase should take care of it for the moment.

**Comment by rburghol** [comment]
Awesome - thanks!

**Comment by rburghol** [comment]
Thanks for these!  I will check them out asap.

**Comment by rburghol** [comment]
Just looping back. I did a pull this morning.  The first of the 2 example codes you gave ran without error:
```
./cmake-build-dir/ngen ./data/catchment_data.geojson "" ./data/nexus_data.geojson "" ./data/example_realization_config.json
```

However the 2nd did not (where you request only 2 of the 3 catchments). I wasn't sure if you thought those were actually part of the merge that you did or not, so I figured I'd report back.  FWIW, I did not have a cmake-build-debug in the directory, so I modified the command to use the standard "cmake-build-dir", so if that's why it failed, my bad.
```
./cmake-build-dir/ngen ./data/catchment_data.geojson "cat-27,cat-52" ./data/nexus_data.geojson "nex-26,nex-34" ./data/example_realization_config.json

Hello there 0.1.0
Building Nexus collection
Building Catchment collection
Running Models
Output Time Index: 0
        Catchment cat-27 contributing 0.194581 m/s to nex-26
                The modified response is: 3.68761e+06
WARNING: Reservoir calculated a storage above the maximum storage.
WARNING: Reservoir calculated a storage above the maximum storage.
        Catchment cat-52 contributing 0.000694444 m/s to nex-34
                The modified response is: 15027.3
        Catchment cat-67 contributing 0.194581 m/s to
Segmentation fault (core dumped)

```

**Comment by rburghol** [comment]
@hellkite500 - thanks and no worries on the delay. Before you spend any time, let me try this again on a completely fresh install to make sure there was nothing in the (re)compile process that caused this. I'll get back this week.

**Comment by rburghol** [comment]
I just did a totally fresh install on this, including re-installing boost (and fixing a typo in my procedure for that above).  All tests **and** the example watershed simulation ran without error -- Thanks for moving this along!

**Comment by ZacharyWills** [comment]
Okay to close?
