### ISSUE TITLE
Run Failure (Python Version)

### ISSUE THREAD

**Issue by ZacharyWills** [NOAA-OWP/ngen#262]
Action Testing fails to run nGen

## Current behavior
Failure to build and run nGen in Actions here:

https://github.com/NOAA-OWP/ngen/actions/runs/1027692345

Problem section:
```
-- Found Boost: /ngen/boost_1_72_0 (found suitable version "1.72.0", minimum required is "1.72.0")  
1561
INFO NGEN_ACTIVATE_PYTHON not defined
1562
INFO Did not find 'PYTHON_INCLUDE_DIR' in ENV
1563
INFO Did not find 'PYTHON_LIBRARIES' in ENV
1564
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
1565
  Could NOT find Python: Found unsuitable version "3.6.8", but required is at
1566
  least "3.6.12" (found , found components: Interpreter)
1567
Call Stack (most recent call first):
1568
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:456 (_FPHSA_FAILURE_MESSAGE)
1569
  /usr/share/cmake/Modules/FindPython/Support.cmake:2966 (find_package_handle_standard_args)
1570
  /usr/share/cmake/Modules/FindPython.cmake:393 (include)
1571
  CMakeLists.txt:130 (find_package)
1572

```

## Expected behavior
nGen should build and run in GitHub Actions

## Steps to replicate behavior (include URLs)

1. Run action

**Comment by ZacharyWills** [comment]
I can try and boost the version of python in the image, or run an update prior since it looks like just a minor version update with fix the issue.

However @robertbartel is that ENV something that just needs to be set in the action?

**Comment by jdmattern-noaa** [comment]
Not sure of best method with Docker, but I would recommend setting up a venv in the project root.

**Comment by ZacharyWills** [comment]
This has been fixed! Thanks!
