### ISSUE TITLE
Documentation isn't being updated correctly

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/ngen#277]
If you go to the gh-pages branch, you can see all of the files that have been created for the documentation. Despite the system changing, only what appears to be the first versions of each page are kept. Many pages, for instance, are 2 years old. Those pages are, oddly enough, pages that feature a table of contents. As a result, if you navigate to the documentation. New classes and namespaces aren't listed.

This needs to be updated so that the full set of pages are updated on every run and everything is correctly pushed to the branch upon generation.

**Comment by christophertubbs** [comment]
The checkout action bears the line:

`/usr/bin/git checkout --progress --force -B gh-pages refs/remotes/origin/gh-pages`

I could be wrong, but I believe that switches over to the gh-pages branch (what we want) but blasts away all we have with what already exists (what we don't want). I can't find where that can be modified within that action, so that logic may need to be done manually.

**Comment by stcui007** [comment]
How complicated is it to do it manually just to prove your theory/hypothesis?

**Comment by stcui007** [comment]
I find the following web page which may or may not be relevant, it describes an action/checkout step.
https://github.com/marketplace/actions/deploy-to-github-pages

**Comment by mattw-nws** [comment]
@christophertubbs Yes that's precisely correct... but that arguably shoudn't have to change. It appears what happened here is that the contents of `docs/html` should never have been committed into the `gh-pages` branch, but they were ...otherwise that command would be fine. Since the files are only _copied_ out of that directory to the root instead of _moved_, those deeper copies got committed the first time, and interfere with/override subsequent runs. I think if we blow away the contents of `docs/html` (and add a `.gitignore` placeholder) and change that `cp` to a `mv` that should do the trick.

**Comment by stcui007** [comment]
Matt,
Would you be able to check https://mattw-nws.github.io/ngen/ to see if the web page generate all namespaces and classes?

**Comment by mattw-nws** [comment]
I think I would have to enable GitHub pages for myself... I think I can do that. I may need to perform another commit to get the workflow to run in my fork...or something. Not sure if the workflows run/work automatically in my fork already or not...probably not?

**Comment by stcui007** [comment]
When I click on my own page. It displays something but not what I wanted to see. When I tried to display your page, I got a 404 error. But since I am not an owner thought you might be able to see it.

**Comment by mattw-nws** [comment]
Okay so https://mattw-nws.github.io/ngen/annotated.html now works, it still looks the same, but I expect that... to fix it the workflow has to run now (in my fork)...

**Comment by mattw-nws** [comment]
It looks as though that worked! https://mattw-nws.github.io/ngen/namespaces.html

So, if you manually wipe out the docs directory _in the `gh-pages` branch_ and commit to that branch, and then immediately merge #280 , it should fix it. Better, probably, is to merge #280 and then delete/commit docs to `gh-pages`... preventing the risk of any other action kicking off the workflow and re-adding the docs directory.

**Comment by stcui007** [comment]
Awesome. It looks great!

**Comment by mattw-nws** [comment]
The remaining part of the fix fixed itself--a subsequent run of the workflow committed the removal of the `docs` folder (in f3fbc290)...so this can be closed.
