### ISSUE TITLE
Automatically Build ISO C Middleware

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/ngen#333]
Currently, in order to use the BMI Fortran integration, the middleware library at `extern/iso_c_fortran_bmi/` has to be built.   Since it is treated like a separate, external CMake project, that isn't being done automatically. 

However, with #323, we now (or very shortly will) have an example added for automatically building an external project as a dependency of an internal build target or library.   The build configuration should be adjusted to do something similar for `extern/iso_c_fortran_bmi/` when BMI Fortran functionality is active.

**Comment by robertbartel** [comment]
Make sure to update the step on building the Fortran middleware on the [tutorial wiki page](https://github.com/NOAA-OWP/ngen/wiki/NGen-Tutorial) once this is done.

**Comment by mattw-nws** [comment]
Working on this in https://github.com/mattw-nws/ngen/tree/one-punch-man .

**Comment by hellkite500** [comment]
Closed by #694
