### ISSUE TITLE
Unexpected change to RAIN_RATE value which is supposed to be passthrough in CFE

### ISSUE THREAD

**Issue by mattw-nws** [NOAA-OWP/ngen#371]
Output column `RAIN_RATE` has different values vs. the `RAINRATE` values in forcing data when running Noah+CFE.

## Current behavior

See attachments for one catchment (unclear if this occurs on all catchments?)

## Expected behavior

Output values should be identical to output.

## Steps to replicate behavior (include URLs)

Run Noah+CFE with forcing data with some `RAINRATE` data and compare with output `RAIN_RATE` column

## Screenshots

[cat-13581_output.csv](https://github.com/NOAA-OWP/ngen/files/7972766/cat-13581_output.csv)
[cat-13581_forcing.csv](https://github.com/NOAA-OWP/ngen/files/7972767/cat-13581_forcing.csv)

**Comment by lcunha0118** [comment]
Hi @mattw-nws, the values do not have to be the same. NOAH-MP has processes as interception and snow that change the input of water to CFE. What is being printed out of CFE is the output from NOAH-MP (QINSUR) and not the input (forcing).

**Comment by mattw-nws** [comment]
@lcunha0118 that's super helpful... @stcui007 can you confirm if this is the cause of what you observed?

**Comment by stcui007** [comment]
I am checking. Looking at the config json data, QINSUR is the main output
variable. Does NOAH-MP only output this one variable, and this is written
out in the RAIN_RATE column?

**Comment by lcunha0118** [comment]
NOAH-MP outputs two variables that are used for CFE. You can see them in the realization file, variables_names_map:
                               
     "water_potential_evaporation_flux": "EVAPOTRANS",
    "atmosphere_water__liquid_equivalent_precipitation_rate": "QINSUR"

The first listed is CFE input, second NOAH-MP output.

**Comment by SnowHydrology** [comment]
@lcunha0118 is correct. If we are running Noah-OWP-Modular plus CFE we would not expect "RAINRATE" from the forcing data to match the "RAIN_RATE" output from CFE. Why? Noah-OWP-Modular includes routines that modify incoming precipitation, whereas CFE on its own does not. These include processes like interception by vegetation and snow accumulation and melt. 

Additionally, we **need** to move away from the RAINRATE naming convention. At best it's confusing and at worst it's wrong. Precipitation ≠ RAINRATE.

**Comment by stcui007** [comment]
I have attached two files: the forcing input and the output from
NOAH-MP-CFE. Looking at the RAIN_RATE column from the two files, much of
the RAIN_RATE from the forcing are reduced to zero. Is that due to ET or
some other processes?

**Comment by lcunha0118** [comment]
Yes, you are simulating a January month, so snow is accumulating.

**Comment by stcui007** [comment]
Just to make sure. So RAIN_RATE in the output is actually QINSUR and QINSUR
only includes the liquid water.

**Comment by SnowHydrology** [comment]
And a small note of clarification: We do not use Noah-MP anymore. Our model implementation is Noah-OWP-Modular.
