### ISSUE TITLE
T-route integration tests are broken, interim fix action?

### ISSUE THREAD

**Issue by mattw-nws** [NOAA-OWP/ngen#416]
[Merge tests are failing](https://github.com/NOAA-OWP/ngen/runs/6459193710?check_suite_focus=true) because the latest Cython version (Cython-0.29.29) causes t-route to fail to build. Fixing t-route may be a longer-term action (t-route probably doesn't need to build against that version in production).

What to do in the interim to get build tests passing? E.g. (not exhaustive):

* Disable t-route integration tests
* Pre-install Cython 0.29.28 in the workflow runner, which will probably stop the .29 version from being downloaded
* Other?

**Comment by hellkite500** [comment]
A simple edit on the upstream branch would temporarily resolve this:
changing `Cython` to `Cython==0.29.28` in the [requirements.txt](https://github.com/NOAA-OWP/t-route/blob/ngen/requirements.txt) here, and then a submodule update on ngen would ensure that the ngen branch is pinned to that pip version when installing the dependencies in the runner.

**Comment by mattw-nws** [comment]
That was the other one I was going to include in my list and forgot. Since we have an `ngen` branch yeah we can do that. All of these seem like things that could get overlooked... but actually, that one should get noticed/reviewed when we finally merge the ngen branch and master...so maybe that is the best way.

**Comment by mattw-nws** [comment]
Cython [0.29.29 was yanked](https://pypi.org/project/Cython/0.29.29/), 0.29.30 lets it build fine.
