### ISSUE TITLE
Refactor simple_v1 kernel

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#43]
https://github.com/NOAA-OWP/ngen/blob/0b3aa8b30af185cc22fbeb75ede83a3e9960aea7/models/kernels/simple_v1.cpp#L26

This file was committed (I believe) for its infil() function.  If this is the kernel functionality we want, we need to remove main().  I would recommend moving the test code in main into a unit test.

**Comment by hellkite500** [comment]
#46 addressed the refactor of the infil() function, but test code should still be added as a unit test.

**Comment by hellkite500** [comment]
simple_v1 is deprecated in #47.  Will open a new issue for testing schaake_partitioning

**Comment by stcui007** [comment]
I see some code in ngen/test/models/hymod/include/. Is that where the test
code would go?

Shengting

**Comment by hellkite500** [comment]
Per the readme in ngen/test:

```
Use Analogous Paths
To help with finding associated test code files, mirror the directory structure under test/ of the path to the associated source file. E.g., functions defined in models/hymod/include/Hymod.h should have unit tests in test/models/hymod/include/HymodTest.cpp.
```

So I would create a unit/integration test in a new directory, test/models/kernels.
