### ISSUE TITLE
Consolidate date/time functionality

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#44]
https://github.com/NOAA-OWP/ngen/blob/0b3aa8b30af185cc22fbeb75ede83a3e9960aea7/models/kernels/simple_v1.cpp#L333

https://github.com/NOAA-OWP/ngen/blob/0b3aa8b30af185cc22fbeb75ede83a3e9960aea7/models/kernels/Pdm03.h#L160

These two kernels have duplicate code for date/time handling, this needs to be refactored.

**Comment by stcui007** [comment]
Will work on it.

Shengting

**Comment by stcui007** [comment]
The time functions are only present in Pdm03.h.

**Comment by PhilMiller** [comment]
The listed files have both been deleted from ngen, but repeat instances still exist in

https://github.com/NOAA-OWP/evapotranspiration/blob/9e8cd7c915fe75e0540f874805b858321dc4a5b5/src/pet.c#L529
and
https://github.com/NOAA-OWP/cfe/blob/f4a613e8fda8d51a733c3720c0998000b6a44bb5/src/bmi_cfe.c#L3431

Regardless, they're separated, and not an issue with ngen code, so I'm just going to close this.
