### ISSUE TITLE
Update infil kernel to conform to naming standard

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#45]
https://github.com/NOAA-OWP/ngen/blob/0b3aa8b30af185cc22fbeb75ede83a3e9960aea7/models/kernels/simple_v1.cpp#L120

The infiltration interface should have descriptive parameter names with units and appropriate documentation.

**Comment by stcui007** [comment]
Fred didn't want changes to his original code so that he could read it
easily. Should we leave this for the future?

Shengting

**Comment by hellkite500** [comment]
If we want to retain this kernel in this repository, then it needs to be updated, I opened this issue so that we don't forget to do so.  Not the highest priority right now, but if we have some time it wouldn't hurt.

**Comment by stcui007** [comment]
We have thoroughly compared the code to its Fortran equivalent so we can be
reasonably confident it works correctly. We can do a complete rewrite in
C++ with everything conforming to the standard in the not too distant
future.

Shengting

**Comment by hellkite500** [comment]
@fred-ogden is going to work on addressing this issue.

**Comment by hellkite500** [comment]
Resolved with #47.
