### ISSUE TITLE
Building ngen with python off fails with errors

### ISSUE THREAD

**Issue by stcui007** [NOAA-OWP/ngen#477]
When building the ngen executable with python turned off, the compile fails. The reason is the  ‘InterpreterUtil’ is not guarded with macro in a couple of places in Bmi_Multi_Formulation_Test.cpp.

## Current behavior
Bmi_Multi_Formulation_Test.cpp:30:28: error: ‘InterpreterUtil’ was not declared in this scope
     static std::shared_ptr<InterpreterUtil> interperter;
Bmi_Multi_Formulation_Test.cpp:451:17: error: ‘InterpreterUtil’ was not declared in this scope
 std::shared_ptr<InterpreterUtil> Bmi_Multi_Formulation_Test::interperter = InterpreterUtil::getInstance();

## Expected behavior
Clean build without above message

## Steps to replicate behavior (include URLs)
cmake -B cmake_test -S . -DNGEN_ACTIVATE_PYTHON:BOOL=OFF -DBMI_C_LIB_ACTIVE:BOOL=ON -DBMI_FORTRAN_ACTIVE:BOOL=ON

make -j 8 -C cmake_test

**Comment by mattw-nws** [comment]
Closed by #478
