### ISSUE TITLE
Build tests failed.

### ISSUE THREAD

**Issue by ZacharyWills** [NOAA-OWP/ngen#48]
Short description explaining the high-level reason for the new issue.

## Current behavior
Build tests exits Code 2

## Expected behavior
All Tests: Build and Pass

## Steps to replicate behavior (include URLs)

1.https://github.com/ZacharyWills/ngen/runs/577718969

**Comment by hellkite500** [comment]
@jdmattern-noaa looks like a few references to refactored variables didn't get updated.

**Comment by jdmattern-noaa** [comment]
Okay I will fix thanks. @jdmattern-noaa

**Comment by jdmattern-noaa** [comment]
I will fix over the weekend or Monday morning.

**Comment by ZacharyWills** [comment]
failed new merge also, could be the same cause:
https://github.com/ZacharyWills/ngen/actions/runs/77295822

**Comment by ZacharyWills** [comment]
test badge:
![C/C++ CI](https://github.com/ZacharyWills/ngen/workflows/C/C++%20CI/badge.svg)

**Comment by ZacharyWills** [comment]
Appears to be passing now. We can close.
https://github.com/ZacharyWills/ngen/runs/583343310

Also badge seems to work.
