### ISSUE TITLE
Utility.hpp needs to be updated or removed.

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#49]
The code in model/kernel/utility.hpp is legacy code used to support the testing of some translated kernels.  This has memory allocation using malloc() which should be replaced with more c++ centric memory management, i.e. vectors for arrays of double/float.

**Comment by stcui007** [comment]
I'll take a look at it.

Shengting

**Comment by stcui007** [comment]
The change has been made to use vector instead of malloc(). Please review the most recent utility.hpp.

**Comment by hellkite500** [comment]
Utility.h updated by #102 so closing this for now. May decide later to remove.
