### ISSUE TITLE
Running CFE fails with error related with 'ice_fraction_schaake'

### ISSUE THREAD

**Issue by adlzanchetta** [NOAA-OWP/ngen#498]
Hi all, a **newbie** here.

I followed [this tutorial](https://github.com/NOAA-OWP/ngen/wiki/NGen-Tutorial), successfully built NexGen and successfully run the [first example](https://github.com/NOAA-OWP/ngen/wiki/NGen-Tutorial#running-cfe) of simulation (entitled **Running CFE** but the realization runs a PET, not CFE).

In my learning pathway, I tried to run a simplistic model with CFE for a system with 4 catchments and 3 nexus in an "Y" topological shape. Relevant files are attached.

## Current behavior

When I run ```ngen```, after ```Running timestep 0```, I get some warnings regarding issues with unit conversion and it finally breaks with:

```
(...)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot get forcing value for unrecognized parameter name 'ice_fraction_schaake'.
Aborted (core dumped)
```

From the [CFE repository](https://github.com/NOAA-OWP/cfe), the `ice_fraction_schaake`  is provided by the module SFT, which could be disabled with parameter ```sft_coupled=false```. I included this parameter in the config file (attached ```cfe_uniform.input``` ), tried to use Xinanjiang partitioning scheme, and kept getting the same output.

## Expected behavior

Or ```ngen``` to complete the run gracefully not using SFT, or to get an error complaining about the lack of `ice_fraction_xinan` when using the Xinanjiang partitioning scheme.

## Questions

1. Shouldn't the `ice_fraction_[schaake/xinan]` only be a parameter when ```sft_coupled=true``` ?

2. Is there an place (like a forum or so) for questions and discussions like this (that are more related with usage/how-to than development)?

[cfe_uniform.txt](https://github.com/NOAA-OWP/ngen/files/11006860/cfe_uniform.txt)
[forcings_uniform.csv](https://github.com/NOAA-OWP/ngen/files/11006861/forcings_uniform.csv)
[realization.txt](https://github.com/NOAA-OWP/ngen/files/11006862/realization.txt)

**Comment by hellkite500** [comment]
@adlzanchetta

Thanks for filing this issue, it is a good reminded that the wiki tutorial has gotten out of date with some of our recent developments.

With the addition of `ice fraction` to CFE, the old examples do not work correctly.  We do have a module that can be used to provide constant values for these required inputs, but it does require setting up a Multi BMI Realization as you can see in [this example](https://github.com/NOAA-OWP/ngen/blob/master/data/test_bmi_multi_realization_config.json).  You can remove the fortran noaa-owp-modular part of this realization and use just the C++ Sloth module and the CFE module and that should allow you to run CFE in your test setup.
