### ISSUE TITLE
Variable naming consistency in schaake_partitioning

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#50]
https://github.com/NOAA-OWP/ngen/blob/f9ff236685f22322d21e1fe8d2745d94adf486f1/models/kernels/schaake_partitioning.hpp#L25
https://github.com/NOAA-OWP/ngen/blob/f9ff236685f22322d21e1fe8d2745d94adf486f1/models/kernels/schaake_partitioning.hpp#L32
https://github.com/NOAA-OWP/ngen/blob/f9ff236685f22322d21e1fe8d2745d94adf486f1/models/kernels/schaake_partitioning.hpp#L35

To be consistent with variable naming conventions, all variables should be lowercase

**Comment by stcui007** [comment]
I can fix that. Am reviewing the code to make sure it produces the same
results as before.

Shengting

**Comment by stcui007** [comment]
The requested change has been made in a PR.

**Comment by hellkite500** [comment]
Closed by #102
