### ISSUE TITLE
Odd forcing file format failure when using `SWDOWN`+`LWDOWN`

### ISSUE THREAD

**Issue by mattw-nws** [NOAA-OWP/ngen#504]
## Current behavior

Using one of the older-style forcing files, with a header like this:
```
Time,RAINRATE,T2D,Q2D,U2D,V2D,PSFC,SWDOWN,LWDOWN
2015-12-01 00:00:00,0,285.8000183,0.0093,-2.299999952,0.100000001,100310,0,361.3000183
```
blows up, with some kind of time indexing issue...The error is
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  Forcing had bad init_time 0 for value request
```
It seems forcing specific. I get a similar error if I use a NetCDF forcing built from the same file.

This is the weird part: If I change that header to either of these forms, everything works:
```
Time,RAINRATE,T2D,Q2D,U2D,V2D,PSFC,DSWRF_surface,LWDOWN
2015-12-01 00:00:00,0,285.8000183,0.0093,-2.299999952,0.100000001,100310,0,361.3000183
```
or
```
Time,RAINRATE,T2D,Q2D,U2D,V2D,PSFC,SWDOWN,DLWRF_surface
2015-12-01 00:00:00,0,285.8000183,0.0093,-2.299999952,0.100000001,100310,0,361.3000183
```
one or the other of SW rad or LW rad has to use the AORC-style names... but it doesn't matter which!

This seems like something that could be related to the builtin `et_calc` but I could not see any evidence that this was being used... the formulation being used was tested with the PET module and with Noah's `ETRAN` output being fed to CFE's ET input.

Notably, removing CFE from the formulation made the problem go away... so that is related, but CFE itself is not likely to be the cause.

## Expected behavior

These headers should work for both CSV and NetCDF format.

## Steps to replicate behavior (include URLs)

1. Use the data/gauge_01073000 dataset in PR #502 , and change the headers to the examples above.
2. Create a NetCDF version of the forcing with those headers using the Python script in /utilities and the same behavior occurs.

**Comment by mattw-nws** [comment]
@stcui007 Since #599 and other changes, this may have changed. Can you try to replicate this bug, and if it still happens, try to see what might be causing it?

**Comment by stcui007** [comment]
I'll look into it.
