### ISSUE TITLE
move schaake_test to testing.

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#53]
https://github.com/NOAA-OWP/ngen/blob/8283f3230772360b3393c8eae2544f4e901cd315/models/kernels/schaake_test.cpp#L5

This test code should be moved to the unit testing framework.

**Comment by stcui007** [comment]
Removed   models/kernels/schaake_test.cpp .
Added test/ models/kernels/schaake_test.cpp.

New pull request seems not needed.

Shengting

**Comment by hellkite500** [comment]
To be more specific, the "test" that this perfroms needs to be added to the automated testing, for example, see the hymod test: https://github.com/NOAA-OWP/ngen/blob/master/test/models/hymod/include/HymodTest.cpp

**Comment by stcui007** [comment]
Do you mean I need to write a unit test code for it?

Shengting

**Comment by stcui007** [comment]
Nels,
See if I understand it better this time. To be able to do the automated
testing, I need to run a bunch of cmake commands with related options etc.
I remember working with David on this and got stopped due to lack of cmake
3 on adp-dev1.

Shengting

**Comment by hellkite500** [comment]
Closed by #102
