### ISSUE TITLE
Fail execution if `output_variables` has invalid entries

### ISSUE THREAD

**Issue by ajkhattak** [NOAA-OWP/ngen#535]
## Current behavior
 - In the `output_variables` list at the multi_bmi level, if the user provides a variable that does not exist in the BMIs, then the framework ignores that high-level `output_variables` list and outputs the variables of the vary last BMI instead of `throwing an error `

## Expected behavior
 - If a variable listed in the `output_variables` at the multi_bmi level does not exist, the framework should stop the execution and let the user know that the variable(s) provided does not exist in any of the BMI output variables

## Screenshots
If all variables in the `output_variables` exist in the BMIs, the output looks like this
<img width="347" alt="Screen Shot 2023-06-20 at 7 02 09 PM" src="https://github.com/NOAA-OWP/ngen/assets/15165757/d31c9835-0936-4c00-a859-af48382ec0aa">

and when a variable `var_DNE` does not exist, the output looks like this -- a mismatch between the header size and the data points.
<img width="1272" alt="Screen Shot 2023-06-20 at 7 02 59 PM" src="https://github.com/NOAA-OWP/ngen/assets/15165757/b92ee7a2-7c1d-48eb-92df-e94bc4daee2b">

The realization file used in the above examples is attached here (CFE+PET+SLoTH example).
[realization_cfe_pet.json.zip](https://github.com/NOAA-OWP/ngen/files/11808608/realization_cfe_pet.json.zip)

**Comment by mattw-nws** [comment]
@stcui007 ... Per discussion we had earlier, I double-checked and in this example file the `output_variables` and `output_header_fields` are in the _right_ place--that is, the top-level of the multi-BMI formulation, _not_ on the last BMI module inside the multi-BMI. So this is a valid issue and the example is good.

**Comment by stcui007** [comment]
@Matthew Williamson - NOAA Federal ***@***.***>   I did
run some tests with the provided config file last week. So we want to make
the change to the ngen code so that it complies with the Expected behavior?
