### ISSUE TITLE
Compilation Bug for Unit Tests in Certain Environments

### ISSUE THREAD

**Issue by jdmattern-noaa** [NOAA-OWP/ngen#55]
## Current behavior
Compiler version: g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CMake version: cmake3 version 3.14.6

Bug not present for other users with previous compiler versions.

Errors from:
ngen/test/geojson/JSONGeometry_Test.cpp
ngen/test/geojson/Feature_Test.cpp

Multiple instances of this line in both files cause compilation errors:
stream = std::stringstream();

Compiles fine when corrected to:
stream.str("");

## Expected behavior
PR to follow with this fix.

## Steps to replicate behavior (include URLs)

1. Clone repo: git clone https://github.com/NOAA-OWP/ngen.git
2. cd ngen
3. Update googletest: git submodule update --init --recursive -- test/googletest
4. Create build directory:  cmake -DCMAKE_BUILD_TYPE=Debug -B cmake-build-debug -S
5. Compile with CMake:  cmake --build cmake-build-debug --target test_unit -- -j 4

**Comment by hellkite500** [comment]
Closed by #56
