### ISSUE TITLE
Issues regarding plugging in own Python model (BMI connection & debugging mode)

### ISSUE THREAD

**Issue by RY4GIT** [NOAA-OWP/ngen#571]
We ([@RY4GIT](https://github.com/RY4GIT/) and [@taddyb](https://github.com/taddyb)) attempted to integrate [our own Python model](https://github.com/NWC-CUAHSI-Summer-Institute/cfe_py/tree/add-bmi2) into NGen using the BMI Python. However, we encountered the following issues. 

## Current behavior
1. Bmi_Py_Adapter is having issues connecting the Python to C++ code. It throws an error message 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  (Bmi_Py_Adapter) Failed determining analogous C++ type for Python model '0' type with size 8 bytes.
```
2. Even with the debugging flag enabled (verbose mode), Python warning or error statements are not displayed in the terminal output. When issues arise, it prints only the error message from ngen and the message `Aborted`. This makes it challenging to debug

## Expected behavior
1. Ngen adapts to the latest bmi_python (especially Bmi_Py_Adapter)
2. When the debugging flag is enabled in NGen, Python warning or error statements get printed in the terminal output

## Steps to replicate behavior
1. Git clone [the Python model of interest](https://github.com/NWC-CUAHSI-Summer-Institute/cfe_py/tree/add-bmi2)
`git clone https://github.com/NWC-CUAHSI-Summer-Institute/cfe_py/tree/add-bmi2`
2. Build python environment using [cfe_py/environment.yml](https://github.com/NWC-CUAHSI-Summer-Institute/cfe_py/blob/add-bmi2/environment.yml)
`conda env create -f environment.yml`
5. Activate the venv `conda activate cfe`
6. Build the ngen following [this instruction](https://github.com/NOAA-OWP/ngen/blob/master/INSTALL.md). Before running the building code (`cmake -B /ngen -S . && cmake --build . --target ngen`), turn on the debugging option using `target_compile_options (ngen PUBLIC -g)` in the root CMakeList.txt, as [described here](https://github.com/NOAA-OWP/ngen/tree/master)
7. Run the ngen `./ngen`, and it prints the following. 
```
Build Info:
  NGen version: 0.1.0
  Python active
    Embedded interpreter version: 3.10.12

Python Environment Info:
  VIRTUAL_ENV environment variable: (not set)
  Discovered venv: None
  System paths:

    /home/flipl/miniconda3/lib/python310.zip
    /home/flipl/miniconda3/lib/python3.10
    /home/flipl/miniconda3/lib/python3.10/lib-dynload
    /home/flipl/.local/lib/python3.10/site-packages
    /home/flipl/miniconda3/lib/python3.10/site-packages
    /home/flipl/cfe_py
```
8. Inside the `cfe_py `directory, install the Python model of interest 
`pip install -e .`
9. Run the ngen in the environment inside the `cfe_py `using the following command
`../ngen/ngen catchment_data.geojson "cat-67" nexus_data.geojson "nex-68" bmicfe_realization.json`
10. The following error will be displayed, demonstrating the current behavior (1) and (2), where error message from Python is not printed as well as BMI_PY is not connecting correctly:
```
NGen Framework 0.1.0
Building Nexus collection
Building Catchment collection
Not Using Routing
Catchment topology is dendritic.
Running Models
Running timestep 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  (Bmi_Py_Adapter) Failed determining analogous C++ type for Python model '0' type with size 8 bytes.
Aborted
```
10. If we use [other simpler Python model](https://github.com/NWC-CUAHSI-Summer-Institute/bmi-python-module-2022) instead of `cfe_py`, we didn't get the error `what():  (Bmi_Py_Adapter) Failed `

## Some other info
- OS: WSL on Windows 11
- NGen version: 0.1.0
- We also tried running it on ngen by [CIROH-UA docker image](https://github.com/CIROH-UA/CloudInfra) or [ngen installed on CUAHSI-SI Jupyterhub](https://www.hydroshare.org/resource/99a73f5fa5044b3eb70934c085f2307a/), but the current behavior (1) regarding the bmi_python persists for cfe_py. Here is the ngen version on CUAHSI-SI Jupyterhub 
```
NGen Framework 0.1.0
Usage: 
ngen <catchment_data_path> <catchment subset ids> <nexus_data_path> <nexus subset ids> <realization_config_path>
Arguments for <catchment subset ids> and <nexus subset ids> must be given.
Use "all" as explicit argument when no subset is needed.

Build Info:
  NGen version: 0.1.0
  Fortran BMI enabled
  Python active
    Embedded interpreter version: 3.9.16
  Routing active

Python Environment Info:
  VIRTUAL_ENV environment variable: /opt/conda/lib/python3.9
  Discovered venv: /opt/conda/lib/python3.9
  System paths:
    
    /home/jovyan/data
    /opt/src/GB-RFSM
    /opt/conda/lib/python39.zip
    /opt/conda/lib/python3.9
    /opt/conda/lib/python3.9/lib-dynload
    /opt/conda/lib/python3.9/site-packages
    /opt/src/clawpack_src/clawpack-v5-9-0
```

**Comment by hellkite500** [comment]
I believe for 1 and 2, the software is behaving as intended.

There are no python errors/warnings being generated before the framework error is encountered.

The reason you are seeing this particular error is becuase the framework must query the BMI variables and establish type marshaling between the C++ runtime and they python runtime, so it uses the BMI function `GetVarType`.

If you look at the linked model [here](https://github.com/NWC-CUAHSI-Summer-Institute/cfe_py/blob/866c5e5ce2bdc064069abdec23badcaeba859c72/bmi_cfe/bmi_cfe.py#L737C28-L737C28) you will see your BMI model's definition of this function, which is
```python
return self.get_value_ptr(long_var_name)
```
which then indirectly returns 
```python
self._values[var_name]
```

This does NOT return a compatible type, such as `np.int32` or `float`, that the framework recognizes, and it throws the error -- you can see that the value returned is `0`, which ngen is trying to interpert as a type and doesn't know how to

Failed determining analogous C++ type for Python model `'0'` type with size 8 bytes.

As for 3, I'm not sure we have done any work/testing using conda environments with ngen.  I would open that as its own issue though.

**Comment by RY4GIT** [comment]
Thank you so much @hellkite500 for identifying the issue, though it was a wrong BMI definition on our side. I will fix and try it again to make sure the `GetVarType `are all in `np.int32` or `float`. I will split the issue later!

**Comment by RY4GIT** [comment]
Split to NOAA-OWP/ngen/issues/572

**Comment by hellkite500** [comment]
> I will fix and report again after making sure the `GetVarType `are all in `np.int32` or `float`. I will split the issue later!

These are just examples of supported types, not the only supported types.  Most numpy numeric types and python primitive numeric types are supported.
