### ISSUE TITLE
Tests fail to compile when Python is disabled

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#578]
These two tests in Bmi_Multi_Formulation_Test.cpp attempt to directly interact with a BMI_Py_Adapter.  If python support hasn't been enabled in the build, this will cause a compile time error when building these tests.  Note that at runtime, the `setup` of this t est class properly handles the missing python support.

https://github.com/NOAA-OWP/ngen/blob/d8ca23fb3d03e1a9a45e02a6fc84bc4ef5908760/test/realizations/catchments/Bmi_Multi_Formulation_Test.cpp#L778

https://github.com/NOAA-OWP/ngen/blob/d8ca23fb3d03e1a9a45e02a6fc84bc4ef5908760/test/realizations/catchments/Bmi_Multi_Formulation_Test.cpp#L801

These need similar treatment as seen in prior test cases, 

e.g. https://github.com/NOAA-OWP/ngen/blob/d8ca23fb3d03e1a9a45e02a6fc84bc4ef5908760/test/realizations/catchments/Bmi_Multi_Formulation_Test.cpp#L719

**Comment by mattw-nws** [comment]
Introduced in #493, for anyone else who was confused by this.
