### ISSUE TITLE
Fix partitionGenerator for new Hydrofabric format (nex-N->wb-N)

### ISSUE THREAD

**Issue by mattw-nws** [NOAA-OWP/ngen#604]
In the oldest hydrofabrics, `cat-XX` would have `toid` (really `to_id`) of `nex-YY`, and `nex-YY` would point to a `toid` of `cat-YY`, which would in turn point to `nex-ZZ` ... so cat->nex->cat->nex. In most versions for the past year+, `cat-XX` points to `nex-YY`, but `nex-YY` points to `wb-ZZ`... and then `wb-ZZ` points to `nex-AA`--that is, nothing links back to catchments... so it's
```
cat        cat        cat
 v          v          v
nex > wb > nex > wb > nex > wb ...
```
which probably makes more sense and I think follows the HY_Features standard where the previous topology did not.

We have a test case in `data/gauge_01073000` that includes this kind of linkage and `ngen` itself--at least--works*. I think the partitionGenerator probably does not work properly.

* internally, the network ngen is using is a bunch of disconnected pieces--but this actually doesn't matter in ngen--yet--because t-route is the only thing that deals with the linkage. The partitionGenerator does also when doing parallel runs, but ngen currently doesn't care about the resulting disconnected network.

**Comment by PhilMiller** [comment]
Is there some documentation of the Hydrofabric format, and the changes between the previous and current release? Any reference material at all would be helpful

**Comment by mattw-nws** [comment]
Not...really, not at the level we're talking about here. There's this: https://noaa-owp.github.io/hydrofabric/articles/04-data-model-deep-dive.html#data-model which is relevant, but getting out what you need for this is probably going to be introspection of the files.

I thought there was a description in this... I had written something up somewhere, I will go find it.

**Comment by mattw-nws** [comment]
Ah... See also #529 . And I'm updating the description now.

**Comment by PhilMiller** [comment]
Ah, great, thank you. I'll follow up if I need any more clarification.

**Comment by PhilMiller** [comment]
How are cases where a nexus has two outward flows represented?

**Comment by hellkite500** [comment]
Have you found the case? We assume and validate dendritic networks, meaning a Nexus should have no more than 1 to-id...(an out degree of 1)

**Comment by hellkite500** [comment]
Not to say that the case doesn't occur naturally, but handling that case, like braided streams, requires high fidelity input and hydrodynamic/hydraulic modeling. Forcing dendritic networks is a current simplifying assumption that may relax someday, but not in the foreseeable future.

**Comment by PhilMiller** [comment]
https://en.wikipedia.org/wiki/Parting_of_the_Waters is the case in CONUS that @mattw-nws pointed me to when I was first getting my head into the project. I have no idea how the present revision of the NWM hydrofabric represents it.

**Comment by mattw-nws** [comment]
Yes my understanding is that @mikejohnson51 is aggregating out any instances of this to produce a dendritic graph. This came up when we were discussing the Chicago river and its connection to the Mississippi... we observed that that connection is cut in the hydrofabric up near Chicago, IIRC.

**Comment by mikejohnson51** [comment]
Correct - the data should all be typed as network (dendritic), coastal, or internal

**Comment by PhilMiller** [comment]
This is blocked until we have a decision on what we want to do system-wide in terms of Hydrofabric format compatibility, #619

**Comment by PhilMiller** [comment]
There's an observation I made while working on this that I apparently failed to note - if we partition by nexus rather than by catchment, then we can avoid the need for inter-process communication to feed water between separated catchments that flow into a shared nexus. That would obviate the code in `HY_PointHydroNexusRemote`
