### ISSUE TITLE
Working example for MPI

### ISSUE THREAD

**Issue by hariteja-jajula** [NOAA-OWP/ngen#656]
We have installed and built a ngen executable. And trying to run a distributed ngen model with the example shown in the documentation. However, we're facing an issue while running the MPI with multiple processes. 
Could someone please give me instructions how to on run ngen with multiple processes? Also, what sample dataset should I use to test its running state?

**Comment by ZacharyWills** [comment]
The walkthrough script for https://github.com/CIROH-UA/NGIAB-CloudInfra includes a parallel run mode. 

The steps for that start here: https://github.com/CIROH-UA/NGIAB-CloudInfra/blob/c706d596548f9eab906e1bcd655f3e75ca72dac5/docker/HelloNGEN.sh#L43
showing the MPI partitioning (here: https://github.com/CIROH-UA/NGIAB-CloudInfra/blob/c706d596548f9eab906e1bcd655f3e75ca72dac5/docker/HelloNGEN.sh#L53) 
and then the actual MPI run (here: https://github.com/CIROH-UA/NGIAB-CloudInfra/blob/c706d596548f9eab906e1bcd655f3e75ca72dac5/docker/HelloNGEN.sh#L81)

Let me know if that helps!
Zach

**Comment by hellkite500** [comment]
Running in parallel requires a pre-computed partition, see [this wiki page](https://github.com/NOAA-OWP/ngen/wiki/partition%E2%80%90generator) for information on using the partition generator.  Once you have this partition file, you can run the MPI compiled ngen
```sh
mpirun -n 8 ngen  hydrofab.gpkg all hydrofab.gpkg all realization_config.json partition_config.json
```
You can refer to [this guilde](https://github.com/NOAA-OWP/ngen/blob/master/doc/DISTRIBUTED_PROCESSING.md) as well for distributed processing of ngen.  If something still isn't working, please let us know and provide any additional context you can so we can narrow down issues in the documentation, the code, or the configuration!
