### ISSUE TITLE
Update vendored evapotranspiration submodule once fclose fix lands

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/ngen#663]
The current vendored [`evapotranspiration` submodule](https://github.com/NOAA-OWP/ngen/tree/f4ec32362f30a31c7f76c999c7b2386e659f6661/extern/evapotranspiration) contains a file descriptor resource leak that in certain environments can cause NextGen to hang. PR https://github.com/NOAA-OWP/evapotranspiration/pull/28 fixes this issue, but has not been merged. Once this PR has been merged, we should git submodule update.

**Comment by hellkite500** [comment]
I'm prepping that submodule update now, as soon as that patch is merged I'll push it up.
