### ISSUE TITLE
Update example geopkg from stable hydrofabric release

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#669]
The included example geopackage hydrofabric file (https://github.com/NOAA-OWP/ngen/blob/master/data/gauge_01073000/gauge_01073000.gpkg) was subset from the pre-release hydrofabric, and should be checked against the official release and updated if needed.

**Comment by program--** [comment]
To get a new subset:
```sh
hfsubset -l core -o gage_01073000.gpkg -t hl_uri "Gages-01073000"
```

Then, comparing them:

``` r
read_hf <- function(gpkg) {
    list(
        divides   = sf::read_sf(gpkg, "divides"),
        nexus     = sf::read_sf(gpkg, "nexus"),
        flowpaths = sf::read_sf(gpkg, "flowpaths"),
        network   = sf::read_sf(gpkg, "network")
    )
}

old <- read_hf("gauge_01073000.gpkg")
new <- read_hf("gage_01073000.gpkg")

waldo::compare(old, new)
#> `old$divides$has_flowline` is a logical vector (TRUE, TRUE, TRUE, TRUE, TRUE)
#> `new$divides$has_flowline` is an integer vector (1, 1, 1, 1, 1)
#> 
#> `old$flowpaths$has_divide` is a logical vector (TRUE, TRUE, TRUE, TRUE, TRUE)
#> `new$flowpaths$has_divide` is an integer vector (1, 1, 1, 1, 1)
```

<sup>Created on 2023-11-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Looks like the only difference between the pre-release and v2.0 is that the `has_flowline` and `has_divide` columns are integers rather than booleans.
