### ISSUE TITLE
CI: Update github workflow actions for checkout and cache

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#771]
Node.js 16 actions are deprecated and the following warning is issued when running the workflows:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3
```

The these actions both have `@v4` versions built on Node.js 20, and we should update our usage to clear up this deprecation warning.

Files requiring updates

- [x] https://github.com/NOAA-OWP/ngen/blob/c0b621605f4f081ea4096308b618ca9d4846fa53/.github/actions/ngen-build/action.yaml#L111
- [x] https://github.com/NOAA-OWP/ngen/blob/c0b621605f4f081ea4096308b618ca9d4846fa53/.github/workflows/documentation.yml#L23
- [x] https://github.com/NOAA-OWP/ngen/blob/c0b621605f4f081ea4096308b618ca9d4846fa53/.github/workflows/test_and_validate.yml#L34

**Comment by joshkotrous** [comment]
Opened PR #772 to address this issue.

**Comment by hellkite500** [comment]
@joshkotrous thanks for the PR! It looks like that covers all the checkout actions. Still need a couple quick revisions on the cache action as well to fully clear the deprecation warning. Would you like to push a commit for that?
