### ISSUE TITLE
404 on github page

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/ngen#78]
In order for the github pages to work, a _config.yml must be provided. It's in the master branch, but not gh-pages. 

Without it, I believe that it tries to read the source documents from an incorrect directory, preventing data from being properly deployed and resulting in a 404.

**Comment by hellkite500** [comment]
Do we just need to copy the config from the master branch to the gh-pages?  If so, I can make that happen quick.

**Comment by hellkite500** [comment]
The 404 was fixed when a pages theme was selected for the pages. https://noaa-owp.github.io/ngen/ now serves the source documentation.
