### ISSUE TITLE
Improve CSV Reader Class Handling of Missing Files

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/ngen#80]
Improve how the CSV reader class (and associated usages of it) handle cases when an expected file doesn't exist.  Right now the CSV reader itself doesn't fail, but in such cases it doesn't read anything either, leading to inconsistent behavior downstream in program execution.

A particular example was seen in unit testing for forcings.  If the unit test executable is run from the main directory, rather than when inside the build directory, then a relative path needed for the `ForcingTest.TestForcingDataRead` test will not be correct, leading to a crash of the unit test executable.

**Comment by jdmattern-noaa** [comment]
The Forcing PR #83 was just integrated and addresses this with an error being thrown and halting the program if a CSV file is missing. This does not solve the part of that issue of the forcing unit test failing if the directory that the tests are called from is not the build directory and its dependencies on relative paths. A upcoming solution to this part of the issue would also address issue #69, where the problems with these relative paths is discussed.

**Comment by jdmattern-noaa** [comment]
Issue #69 has been fixed and therefore fixes the rest of this issue.
