### ISSUE TITLE
make_unique<>() not supported on gcc 4.8.5

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#81]
RHEL/CentOS 7 gcc tool chain is 4.8.5 and even with --std=c++1y (for c++14) make_unique is not supported.

## Current behavior

Build fails using gcc 4.8.5 with c++14 standards

## Expected behavior

Buildable on RHEL/ContOS 7

##Proposed
add a custom make_unique<>() implementation in utilities with a macro gaurd to enable it for gcc < 4.9

**Comment by ZacharyWills** [comment]
Is there a known working version? We can test both compilers to see when they align after that's added.

**Comment by hellkite500** [comment]
Closed by #106
