### ISSUE TITLE
Update submodules for ABI compatability

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#835]
Given #834 , we need to ensure the ngen submodules supported and automatically built are compatible with the current BMI ABI.  It looks like `SLOTH` and `bmi-cxx` were updated as part of the process, but these were not and need to get updated.

- [x] SoilFreezeThaw 
- [x] SoilMoistureProfiles
- [ ] CFE*

*CFE may need some additional consideration, especially given the v1.0.0 release tag.  [This change](https://github.com/NOAA-OWP/cfe/commit/3c7803a3098c2c2aecac12dff8f003468379441b) may need to be back ported on a bugfix branch and a v1.0.1 release added to ensure this commit carries into v1.  Or we drop support for v1 and only support v2 after that commit?

@PhilMiller is the change from macro to const int in the C interface problematic with the updates on ngen?  Based on my reviews and understanding, I don't *think* it is, but I could be wrong.  If it isn't an issue in our current usage, then the previous comment can likely be safely ignored for the time being.

**Comment by PhilMiller** [comment]
The change to CFE's `bmi.h` for macros vs `const int` affects the CI for other formulation modules that integrate CFE as part of their testing (i.e. they say `#include "bmi_cfe.h" \ #include "bmi.hxx"`), but shouldn't affect ngen itself, since we never compile the different modules together.
