### ISSUE TITLE
Index needs bounds checks

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#88]
https://github.com/NOAA-OWP/ngen/blob/daec5badcafe57f631eefbf61dbe492b54383239/models/kernels/Nonlinear_Reservoir.hpp#L350

This function must bound check the index at minimum to prevent seg faults.  Might also be worth implementing an unordered map "name" outlets.  i.e. `unoderedmap<string, int> outlet_map` then `outlet_map[name] = index`.  Could then lookup by name `outlet_map['lateral_flow']` so this function could take a `string name` arg.

**Comment by jdmattern-noaa** [comment]
Would this unordered_map go in the nonlinear reservoir code or Tshirt.h? If it goes in the nonlinear reservoir, then we would need to pass a name of the outlet at initialization, which is fine, but I guess have an option not to. Tshirt.h is the only model calling this function at this time.

**Comment by hellkite500** [comment]
bounds check implemented in #90
