### ISSUE TITLE
Update README.md to reflect first sprint changes

### ISSUE THREAD

**Issue by ZacharyWills** [NOAA-OWP/ngen#9]
Short description explaining the high-level reason for the new issue.

## Current behavior
README.md exists as per the template but doesn't reflect first sprint changes.

## Expected behavior
README.md should reflect the project at the end of each sprint.

## Steps to replicate behavior (include URLs)

1.

**Comment by hellkite500** [comment]
I updated the readme with some project details.  As this sprint ends, we can make sure it is up to date and then close this issue.
